"""Makeblock mBot2 tools, relayed to the firmware's ``self.mbot.*`` tools.

Stack-chan talks to an mBot2 (CyberPi running the Stacky runtime) over a
1-to-1 BLE link; see ``firmware/components/mbot_link/``. The gateway only
exposes friendly MCP tools, checks their arguments against the same safety
limits, and maps them onto the device tools. The firmware validates and
clamps again, and the mBot clamps a third time, so the gateway is the
first of three independent checks, not the only one.

The limits mirror the "Safety limits" table of Stacky protocol v1
(mblock-stacky-bridge ``docs/protocol.md``) and
``firmware/components/mbot_link/mbot_limits.h``.
"""

from __future__ import annotations

import math
from typing import Any, Final

from mcp.types import Tool

# --- Safety limits (docs/protocol.md; mbot_limits.h) -----------------------
MBOT_MAX_RPM: Final = 60
MBOT_MAX_MOVE_S: Final = 5.0
MBOT_MIN_MOVE_S: Final = 0.1
MBOT_MAX_PROG_S: Final = 30.0
MBOT_MAX_PROG_STEPS: Final = 20
MBOT_ARM_MIN: Final = 40
MBOT_ARM_MAX: Final = 120
MBOT_ARM_HOME: Final = 90
MBOT_GRIP_MIN: Final = 45
MBOT_GRIP_MAX: Final = 120
MBOT_GRIP_HOME: Final = 90
MBOT_OBSTACLE_CM: Final = 10
MBOT_WATCHDOG_S: Final = 3.0
# v1.1 closed-loop steps
MBOT_MAX_STEP_CM: Final = 30
MBOT_MAX_TURN_DEG: Final = 180
MBOT_STEP_SPEED_MIN: Final = 5
MBOT_STEP_SPEED_DEFAULT: Final = 30
MBOT_ODOM_MIN_MS: Final = 100
MBOT_ODOM_MAX_MS: Final = 5000
MBOT_MAX_CMD_ID: Final = 9999
# Firmware refuses longer command text (one BLE write at MTU 512).
MBOT_MAX_PROGRAM_CHARS: Final = 440

#: Subtypes of ``stackchan-event`` frames with ``event_type: "mbot"``.
#: The first seven come from the mBot (``sk_evt``); ``connected`` and
#: ``disconnected`` are generated by the firmware for the BLE link.
MBOT_EVENT_SUBTYPES: Final = frozenset(
    {
        "ready",
        "done",
        "obstacle",
        "stopped",
        "locked",
        "unlocked",
        "button",
        "connected",
        "disconnected",
    }
)

_DIRECTIONS: Final = ("forward", "backward", "left", "right")
_ARM_POSITIONS: Final = ("up", "down", "home")
_GRIP_POSITIONS: Final = ("open", "close", "home")

LIMITS_TEXT: Final = (
    f"Safety limits (enforced by the gateway, Stack-chan and the mBot itself): "
    f"speed 0-100% of {MBOT_MAX_RPM} RPM (about 20 cm/s at 100%); each move lasts "
    f"{MBOT_MIN_MOVE_S}-{MBOT_MAX_MOVE_S:g} s; arm {MBOT_ARM_MIN}-{MBOT_ARM_MAX} deg; "
    f"gripper {MBOT_GRIP_MIN}-{MBOT_GRIP_MAX} deg ({MBOT_GRIP_MIN} closed, "
    f"{MBOT_GRIP_MAX} open); one step at most {MBOT_MAX_STEP_CM} cm, one turn at most "
    f"{MBOT_MAX_TURN_DEG} deg; programs at most {MBOT_MAX_PROG_STEPS} steps and "
    f"{MBOT_MAX_PROG_S:g} s. Forward motion auto-stops below {MBOT_OBSTACLE_CM} cm. "
    f"mbot_stop is always available and always accepted. Tools return as soon "
    f"as the mBot accepts a command; completion arrives later as an 'mbot' "
    f"'done' event."
)

_EMPTY_SCHEMA: Final[dict[str, Any]] = {"type": "object", "properties": {}}

#: gateway tool name -> firmware tool name
MBOT_DEVICE_TOOLS: Final[dict[str, str]] = {
    "mbot_status": "self.mbot.status",
    "mbot_move": "self.mbot.move",
    "mbot_stop": "self.mbot.stop",
    "mbot_set_led": "self.mbot.set_led",
    "mbot_arm": "self.mbot.arm",
    "mbot_gripper": "self.mbot.gripper",
    "mbot_home": "self.mbot.home",
    "mbot_read_sensors": "self.mbot.read_sensors",
    "mbot_run_program": "self.mbot.run_program",
    "mbot_step": "self.mbot.step",
    "mbot_turn": "self.mbot.turn",
    "mbot_odometry": "self.mbot.odometry",
    "mbot_sync": "self.mbot.sync",
}

EXPLORE_LOOP_TEXT: Final = (
    "For exploring, use the stop -> look -> decide -> step loop: while the mBot is "
    "still, look (take_photo, mbot_read_sensors), decide, then send ONE bounded "
    "mbot_step or mbot_turn. The mBot closes the loop on its own encoders/gyro, so a "
    "slow decision or link delay cannot change how far it goes. The tool returns when "
    "the mBot accepts (result has its id); the step ends with an 'mbot' 'done' event "
    "'<id> <reason> dist=<cm> yaw=<deg> t=<ms>' reporting what it ACTUALLY did (reason "
    "target, timeout, obstacle, cmd, button, watchdog, replaced). Before the next step, "
    "check mbot_odometry(done_id=<id>) until that done has arrived."
)


def mbot_tools() -> list[Tool]:
    """MCP tool definitions for the mBot2."""
    return [
        Tool(
            name="mbot_status",
            description=(
                "Status of the Bluetooth link from Stack-chan to the Makeblock mBot2 "
                "robot car: connected, name/address, battery percent, locked (its B "
                "button is an emergency stop that locks it; a person presses A to "
                "unlock) and the limits. " + LIMITS_TEXT
            ),
            inputSchema=_EMPTY_SCHEMA,
        ),
        Tool(
            name="mbot_move",
            description=(
                "Drive the mBot2. left/right turn in place. A new move replaces the "
                "current one. " + LIMITS_TEXT
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "direction": {
                        "type": "string",
                        "enum": list(_DIRECTIONS),
                        "description": "forward, backward, or turn in place left/right.",
                    },
                    "speed_percent": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 100,
                        "default": 40,
                        "description": f"0-100 % of {MBOT_MAX_RPM} RPM. Default 40.",
                    },
                    "seconds": {
                        "type": "number",
                        "minimum": MBOT_MIN_MOVE_S,
                        "maximum": MBOT_MAX_MOVE_S,
                        "default": 1.0,
                        "description": (
                            f"How long to move, {MBOT_MIN_MOVE_S}-{MBOT_MAX_MOVE_S:g} s. "
                            "Default 1."
                        ),
                    },
                },
                "required": ["direction"],
            },
        ),
        Tool(
            name="mbot_stop",
            description=(
                "Stop the mBot2 now: wheels stop, a running program is cancelled. "
                "Always available and always accepted, even when the mBot is locked. "
                "Use it whenever anything looks wrong."
            ),
            inputSchema=_EMPTY_SCHEMA,
        ),
        Tool(
            name="mbot_set_led",
            description="Set the colour of the mBot2's CyberPi LEDs (all, or one of 1-5).",
            inputSchema={
                "type": "object",
                "properties": {
                    "r": {"type": "integer", "minimum": 0, "maximum": 255},
                    "g": {"type": "integer", "minimum": 0, "maximum": 255},
                    "b": {"type": "integer", "minimum": 0, "maximum": 255},
                    "index": {
                        "description": 'LED 1-5, or "all" (default).',
                        "anyOf": [
                            {"type": "string", "enum": ["all"]},
                            {"type": "integer", "minimum": 1, "maximum": 5},
                        ],
                        "default": "all",
                    },
                },
                "required": ["r", "g", "b"],
            },
        ),
        Tool(
            name="mbot_arm",
            description=(
                f"Move the mBot2 arm (servo S4). Give position (up = {MBOT_ARM_MAX}, "
                f"down = {MBOT_ARM_MIN}, home = {MBOT_ARM_HOME} deg) or angle "
                f"{MBOT_ARM_MIN}-{MBOT_ARM_MAX}, not both. It glides at 90 deg/s."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "position": {"type": "string", "enum": list(_ARM_POSITIONS)},
                    "angle": {
                        "type": "integer",
                        "minimum": MBOT_ARM_MIN,
                        "maximum": MBOT_ARM_MAX,
                    },
                },
            },
        ),
        Tool(
            name="mbot_gripper",
            description=(
                f"Open or close the mBot2 gripper (servo S3). Give position (open = "
                f"{MBOT_GRIP_MAX}, close = {MBOT_GRIP_MIN}, home = {MBOT_GRIP_HOME} deg) or "
                f"angle {MBOT_GRIP_MIN}-{MBOT_GRIP_MAX} ({MBOT_GRIP_MIN} closed, "
                f"{MBOT_GRIP_MAX} open), not both."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "position": {"type": "string", "enum": list(_GRIP_POSITIONS)},
                    "angle": {
                        "type": "integer",
                        "minimum": MBOT_GRIP_MIN,
                        "maximum": MBOT_GRIP_MAX,
                    },
                },
            },
        ),
        Tool(
            name="mbot_home",
            description="Move the mBot2 arm and gripper back to 90 deg.",
            inputSchema=_EMPTY_SCHEMA,
        ),
        Tool(
            name="mbot_read_sensors",
            description=(
                "Read the mBot2: dist / distance_cm (ultrasonic cm, null if absent), "
                "battery_percent, arm_deg, gripper_deg, locked, and with runtime v1.1 "
                "left_wheel_cm, right_wheel_cm, yaw_deg, mbot_ms."
            ),
            inputSchema=_EMPTY_SCHEMA,
        ),
        Tool(
            name="mbot_run_program",
            description=(
                "Run a short mini-program on the mBot2. steps are separated by ';', "
                'e.g. "fwd 40 1; led 0 255 0; wait 0.5; arm up". Step forms: '
                "fwd|back|left|right <speed% 0-100> <seconds 0.1-5>; "
                "straight <cm -30..30> [speed% 5-100]; turn <deg -180..180, + = left> "
                "[speed% 5-100]; wait <seconds 0-5>; "
                "led <r> <g> <b> [all|1-5]; arm up|down|home|<40-120>; "
                "grip open|close|home|<45-120>; home. "
                f"At most {MBOT_MAX_PROG_STEPS} steps and {MBOT_MAX_PROG_S:g} s in total "
                "(moves + waits + step/turn time, plus about 1 s per arm/grip/home step); a longer "
                "program is rejected as a whole. mbot_stop aborts it. " + LIMITS_TEXT
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "steps": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": MBOT_MAX_PROGRAM_CHARS,
                        "description": "Steps separated by ';'.",
                    },
                },
                "required": ["steps"],
            },
        ),
        Tool(
            name="mbot_step",
            description=(
                f"Drive the mBot2 straight by a distance, closed-loop on its wheel encoders: "
                f"distance_cm -{MBOT_MAX_STEP_CM}..{MBOT_MAX_STEP_CM} (negative = backwards). "
                f"Forward motion still auto-stops below {MBOT_OBSTACLE_CM} cm. "
                + EXPLORE_LOOP_TEXT
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "distance_cm": {
                        "type": "integer",
                        "minimum": -MBOT_MAX_STEP_CM,
                        "maximum": MBOT_MAX_STEP_CM,
                        "description": "Distance in cm; negative drives backwards.",
                    },
                    "speed_percent": _step_speed_schema(),
                },
                "required": ["distance_cm"],
            },
        ),
        Tool(
            name="mbot_turn",
            description=(
                f"Turn the mBot2 in place by an angle, closed-loop on its gyro: degrees "
                f"-{MBOT_MAX_TURN_DEG}..{MBOT_MAX_TURN_DEG}, positive = left "
                "(counter-clockwise), negative = right. " + EXPLORE_LOOP_TEXT
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "degrees": {
                        "type": "integer",
                        "minimum": -MBOT_MAX_TURN_DEG,
                        "maximum": MBOT_MAX_TURN_DEG,
                        "description": "Angle in degrees; positive = left (CCW).",
                    },
                    "speed_percent": _step_speed_schema(),
                },
                "required": ["degrees"],
            },
        ),
        Tool(
            name="mbot_odometry",
            description=(
                "Read the mBot2 pose information Stack-chan has cached (does not move it). "
                "Returns connected, last_done = the most recent done {id (string), reason, "
                "dist (cm), yaw (deg) actually travelled, t (mBot ms), age_ms} or null, "
                "done = the done for done_id (among the last 8), odom = the latest streamed "
                "{t, l, r (wheel cm), yaw (deg), age_ms} or null, and rtt_ms. Values the mBot "
                "reports as none are null. stream_ms optionally sets the odom "
                f"stream period: 0 = off, {MBOT_ODOM_MIN_MS}-{MBOT_ODOM_MAX_MS} ms."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "done_id": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": MBOT_MAX_CMD_ID,
                        "description": "Command id returned by mbot_step / mbot_turn / mbot_move.",
                    },
                    "stream_ms": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": MBOT_ODOM_MAX_MS,
                        "description": (
                            f"0 = stop streaming, {MBOT_ODOM_MIN_MS}-{MBOT_ODOM_MAX_MS} = period."
                        ),
                    },
                },
            },
        ),
        Tool(
            name="mbot_sync",
            description=(
                "Measure the Bluetooth round trip (rtt_ms) and the mBot2 clock offset "
                "(offset_ms = mbot_ms minus Stack-chan time at the middle of the round trip), "
                "to map mbot_ms timestamps in done/odom events onto Stack-chan time."
            ),
            inputSchema=_EMPTY_SCHEMA,
        ),
    ]


def _step_speed_schema() -> dict[str, Any]:
    return {
        "type": "integer",
        "minimum": MBOT_STEP_SPEED_MIN,
        "maximum": 100,
        "default": MBOT_STEP_SPEED_DEFAULT,
        "description": f"{MBOT_STEP_SPEED_MIN}-100 % of {MBOT_MAX_RPM} RPM. Default 30.",
    }


def _int_in(args: dict[str, Any], key: str, lo: int, hi: int, default: int | None = None) -> int:
    value = args.get(key, default)
    if value is None:
        raise ValueError(f"{key} is required")
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{key} must be an integer {lo}-{hi}")
    if isinstance(value, float):
        if not value.is_integer():
            raise ValueError(f"{key} must be an integer {lo}-{hi}")
        value = int(value)
    if not lo <= value <= hi:
        raise ValueError(f"{key} must be {lo}-{hi} (got {value})")
    return value


def _servo_args(
    args: dict[str, Any], positions: tuple[str, ...], lo: int, hi: int
) -> dict[str, Any]:
    position = args.get("position")
    angle = args.get("angle")
    if position is not None and angle is not None:
        raise ValueError("give either position or angle, not both")
    if angle is not None:
        return {"angle": _int_in(args, "angle", lo, hi)}
    if position not in positions:
        raise ValueError(f"position must be one of {', '.join(positions)} (or give angle {lo}-{hi})")
    return {"position": position}


def map_mbot_call(name: str, arguments: dict[str, Any] | None) -> tuple[str, dict[str, Any]]:
    """Validate a gateway mbot_* call and map it to the firmware tool.

    Raises ``ValueError`` with an LLM-readable message on bad arguments;
    nothing is sent to the device in that case.
    """
    args = dict(arguments or {})
    device_tool = MBOT_DEVICE_TOOLS[name]

    if name in ("mbot_status", "mbot_stop", "mbot_home", "mbot_read_sensors", "mbot_sync"):
        return device_tool, {}

    if name == "mbot_step":
        return device_tool, {
            "distance_cm": _int_in(args, "distance_cm", -MBOT_MAX_STEP_CM, MBOT_MAX_STEP_CM),
            "speed_percent": _int_in(
                args, "speed_percent", MBOT_STEP_SPEED_MIN, 100, default=MBOT_STEP_SPEED_DEFAULT
            ),
        }

    if name == "mbot_turn":
        return device_tool, {
            "degrees": _int_in(args, "degrees", -MBOT_MAX_TURN_DEG, MBOT_MAX_TURN_DEG),
            "speed_percent": _int_in(
                args, "speed_percent", MBOT_STEP_SPEED_MIN, 100, default=MBOT_STEP_SPEED_DEFAULT
            ),
        }

    if name == "mbot_odometry":
        out: dict[str, Any] = {}
        if args.get("done_id") is not None:
            out["done_id"] = _int_in(args, "done_id", 1, MBOT_MAX_CMD_ID)
        if args.get("stream_ms") is not None:
            period = _int_in(args, "stream_ms", 0, MBOT_ODOM_MAX_MS)
            if 0 < period < MBOT_ODOM_MIN_MS:
                raise ValueError(
                    f"stream_ms must be 0 (off) or {MBOT_ODOM_MIN_MS}-{MBOT_ODOM_MAX_MS}"
                )
            out["stream_ms"] = period
        return device_tool, out

    if name == "mbot_move":
        direction = args.get("direction")
        if direction not in _DIRECTIONS:
            raise ValueError(f"direction must be one of {', '.join(_DIRECTIONS)}")
        speed = _int_in(args, "speed_percent", 0, 100, default=40)
        seconds = args.get("seconds", 1.0)
        if (
            isinstance(seconds, bool)
            or not isinstance(seconds, (int, float))
            or not math.isfinite(seconds)
            or not MBOT_MIN_MOVE_S <= seconds <= MBOT_MAX_MOVE_S
        ):
            raise ValueError(
                f"seconds must be a number {MBOT_MIN_MOVE_S}-{MBOT_MAX_MOVE_S:g} (got {seconds!r})"
            )
        return device_tool, {
            "direction": direction,
            "speed_percent": speed,
            "duration_ms": int(round(seconds * 1000)),
        }

    if name == "mbot_set_led":
        out = {k: _int_in(args, k, 0, 255) for k in ("r", "g", "b")}
        index = args.get("index", "all")
        if index == "all":
            out["index"] = "all"
        else:
            out["index"] = str(_int_in({"index": index}, "index", 1, 5))
        return device_tool, out

    if name == "mbot_arm":
        return device_tool, _servo_args(args, _ARM_POSITIONS, MBOT_ARM_MIN, MBOT_ARM_MAX)

    if name == "mbot_gripper":
        return device_tool, _servo_args(args, _GRIP_POSITIONS, MBOT_GRIP_MIN, MBOT_GRIP_MAX)

    if name == "mbot_run_program":
        steps = args.get("steps")
        if not isinstance(steps, str) or not steps.strip():
            raise ValueError("steps must be a non-empty string")
        if len(steps) > MBOT_MAX_PROGRAM_CHARS:
            raise ValueError(f"steps is too long (max {MBOT_MAX_PROGRAM_CHARS} characters)")
        count = len([s for s in steps.split(";") if s.strip()])
        if count > MBOT_MAX_PROG_STEPS:
            raise ValueError(
                f"program has {count} steps; the limit is {MBOT_MAX_PROG_STEPS}"
            )
        return device_tool, {"steps": steps}

    raise ValueError(f"Unknown mbot tool: {name}")  # pragma: no cover
